import { NextResponse } from 'next/server';
import { createClient } from 'next-sanity';

const writeClient = createClient({
  projectId: "1pu795c0",
  dataset: "production",
  apiVersion: "2024-03-12",
  useCdn: false,
  token: process.env.SANITY_API_WRITE_TOKEN,
});

const spotlights = [
  {
    name: "Gaby",
    slug: "gaby",
    heading: "LEADING THE AVIATION OPERATIONS IN MEXICO",
    body: "GABY WORKS IN AVIATION OPERATIONS AT AEROMEXICO, A FIELD WHERE PRECISION, SAFETY, AND LEADERSHIP ARE PART OF EVERYDAY DECISION-MAKING. WITH EXPERIENCE IN CABIN OPERATIONS AND TRAINING ENVIRONMENTS, HER ROLE REQUIRES CONSTANT COLLABORATION, CLEAR COMMUNICATION, AND THE ABILITY TO NAVIGATE HIGH-PRESSURE SITUATIONS WITH CONFIDENCE.\n\nAT THE ATELIER, GABY FOCUSES ON STRENGTHENING HER PROFESSIONAL COMMUNICATION IN ENGLISH THROUGH CONVERSATION-BASED SESSIONS CENTERED ON REAL AVIATION TOPICS—LEADERSHIP, SAFETY CULTURE, TRAINING SYSTEMS, AND INTERNATIONAL INDUSTRY DISCUSSIONS.\n\nRATHER THAN TRADITIONAL LANGUAGE CLASSES, OUR SESSIONS OFTEN TAKE THE FORM OF SIMULATED PANELS, PODCAST INTERVIEWS, AND CONFERENCE-STYLE CONVERSATIONS. THIS ALLOWS GABY TO PRACTICE EXPRESSING COMPLEX IDEAS CLEARLY AND CONFIDENTLY, JUST AS SHE WOULD IN INTERNATIONAL PROFESSIONAL ENVIRONMENTS.\n\nHER JOURNEY REFLECTS WHAT THE ATELIER IS ABOUT: AMBITIOUS PROFESSIONALS USING ENGLISH NOT JUST AS A LANGUAGE SKILL, BUT AS A TOOL TO PARTICIPATE IN GLOBAL CONVERSATIONS WITHIN THEIR INDUSTRIES.",
    imagePath: "pages/gaby.webp"
  },
  {
    name: "Marwa",
    slug: "marwa",
    heading: "GLOBAL LEARNER | MULTICULTURAL PERSPECTIVE",
    category: "ATELIER SPOTLIGHTS — SECOND GENERATION",
    body: "MARWA IS AN ENGLISH LANGUAGE TEACHING STUDENT AT MERSIN UNIVERSITY, WHO JOINED THE ATELIER WITH A STRONG CURIOSITY FOR LANGUAGES AND GLOBAL CULTURES. AS PART OF ATELIER SPOTLIGHTS — SECOND GENERATION, SHE HAS BEEN DEVELOPING HER ABILITY TO COMMUNICATE CONFIDENTLY IN SPANISH WHILE EXPLORING TOPICS CONNECTED TO CULTURE, TRAVEL, AND INTERNATIONAL PERSPECTIVES.\n\nHER PROGRAM FOCUSES ON BUILDING CONVERSATIONAL FLUENCY, EXPANDING VOCABULARY, AND STRENGTHENING THE CONFIDENCE NEEDED TO EXPRESS IDEAS CLEARLY IN REAL-WORLD SITUATIONS.\n\nTHROUGH HER LESSONS, MARWA PRACTICES SPANISH THROUGH DISCUSSIONS ABOUT CULTURE, DAILY LIFE IN DIFFERENT COUNTRIES, AND GLOBAL PERSPECTIVES—ALLOWING LANGUAGE LEARNING TO BECOME A BRIDGE BETWEEN WORLDS.\n\nHER JOURNEY REFLECTS THE SPIRIT OF ATELIER SPOTLIGHTS: WOMEN WHO EMBRACE CURIOSITY, CULTURAL OPENNESS, AND THE DESIRE TO GROW BEYOND BORDERS.",
    imagePath: "pages/marwa.webp"
  },
  {
    name: "Aya",
    slug: "aya",
    heading: "CURIOUS MIND | FUTURE GLOBAL CITIZEN",
    category: "ATELIER SPOTLIGHTS — SECOND GENERATION",
    body: "AYA IS AN INTERNATIONAL RELATIONS MAJOR AT MERSIN UNIVERSITY. PART OF ATELIER SPOTLIGHTS — SECOND GENERATION, A COMMUNITY THAT HIGHLIGHTS WOMEN DEVELOPING THEIR VOICE THROUGH LANGUAGE AND CULTURAL EXPLORATION.\n\nHER SPANISH PROGRAM FOCUSES ON BUILDING STRONG CONVERSATIONAL SKILLS WHILE EXPLORING TOPICS SUCH AS CULTURE, TRAVEL, AND GLOBAL PERSPECTIVES. THROUGH DYNAMIC DISCUSSIONS AND REAL-LIFE SCENARIOS, AYA WILL STRENGTHEN HER CONFIDENCE AND ABILITY TO COMMUNICATE NATURALLY IN SPANISH.\n\nAT THE ATELIER, HER LEARNING JOURNEY CENTERS ON DEVELOPING NOT ONLY LANGUAGE SKILLS BUT ALSO THE ABILITY TO EXPRESS IDEAS, OPINIONS, AND EXPERIENCES WITH CLARITY.\n\nAYA REPRESENTS THE CURIOSITY AND OPENNESS THAT DEFINE THE ATELIER COMMUNITY—WOMEN WHO SEE LANGUAGE AS A GATEWAY TO THE WORLD.",
    imagePath: "pages/aya.webp"
  },
  {
    name: "Saja",
    slug: "saja",
    heading: "NURSE | HEALTHCARE PROFESSIONAL",
    category: "ATELIER SPOTLIGHTS — SECOND GENERATION",
    body: "SAJA IS A HEALTHCARE PROFESSIONAL GRADUATED FROM MERSIN UNIVERSITY, WORKING AS A NURSE WITH A STRONG INTEREST IN LANGUAGES, CULTURE, AND INTERNATIONAL COMMUNICATION.\n\nSHE FIRST JOINED THE ATELIER THROUGH A PERSONALIZED ART & CULTURE SPANISH PROGRAM, WHERE SPANISH WAS EXPLORED THROUGH CREATIVE TOPICS SUCH AS ART, CULTURE, AND VISUAL STORYTELLING. THIS APPROACH ALLOWED HER TO DEVELOP CONVERSATIONAL SKILLS WHILE DISCUSSING CULTURAL SUBJECTS THAT MADE THE LEARNING PROCESS ENGAGING AND INTELLECTUALLY STIMULATING.\n\nTHROUGHOUT HER PROGRAM, SAJA WORKED ON:\n• DEVELOPING GENERAL SPANISH SKILLS\n• BUILDING CONFIDENCE IN CROSS-CULTURAL COMMUNICATION\n• EXPANDING VOCABULARY RELATED TO CULTURE, TRAVEL, AND DAILY LIFE\n• DISCUSSING ART, CREATIVITY, AND GLOBAL PERSPECTIVES IN SPANISH\n\nTODAY, SAJA IS PART OF ATELIER SPOTLIGHTS SECOND GEN, A SERIES THAT HIGHLIGHTS WOMEN IN THE ATELIER COMMUNITY WHO ARE DEVELOPING THEIR GLOBAL VOICE THROUGH LANGUAGE.\n\nHER JOURNEY REFLECTS THE DIVERSITY OF THE ATELIER COMMUNITY—BRINGING TOGETHER PROFESSIONALS FROM DIFFERENT FIELDS WHO SHARE CURIOSITY, AMBITION, AND A DESIRE TO CONNECT WITH THE WORLD THROUGH LANGUAGE.",
    imagePath: "pages/saja.webp"
  },
  {
    name: "Şefika Buse",
    slug: "buse",
    heading: "INTERNATIONAL RELATIONS STUDENT | ERASMUS SCHOLAR",
    category: "ATELIER SPOTLIGHTS — SECOND GENERATION",
    body: "ŞEFIKA BUSE IS AN INTERNATIONAL RELATIONS STUDENT AT MERSIN UNIVERSITY, CURRENTLY COMPLETING AN ACADEMIC EXCHANGE IN POLAND THROUGH THE ERASMUS PROGRAMME.\n\nBUSE JOINED THE ATELIER TO STRENGTHEN HER SPANISH AND EXPAND HER ABILITY TO COMMUNICATE ACROSS CULTURES—AN ESSENTIAL SKILL FOR A FUTURE CAREER IN INTERNATIONAL AFFAIRS.\n\nAS PART OF ATELIER SPOTLIGHTS — SECOND GENERATION, HER SPANISH PROGRAM COMBINES LANGUAGE LEARNING WITH DISCUSSIONS ON GLOBAL POLITICS, DIPLOMACY, AND INTERNATIONAL COOPERATION, ALLOWING HER TO PRACTICE THE LANGUAGE THROUGH THE SAME TOPICS SHE STUDIES IN HER ACADEMIC PROGRAM.\n\nOVER THE PAST YEAR, HER LESSONS HAVE FOCUSED ON:\n• DEVELOPING CONVERSATIONAL FLUENCY IN SPANISH\n• BUILDING VOCABULARY RELATED TO INTERNATIONAL RELATIONS AND DIPLOMACY\n• DISCUSSING GLOBAL INSTITUTIONS AND GEOPOLITICAL TOPICS\n• STRENGTHENING CONFIDENCE WHEN EXPRESSING COMPLEX IDEAS IN A SECOND LANGUAGE\n\nTHROUGH HER ERASMUS EXPERIENCE, BUSE REGULARLY INTERACTS WITH STUDENTS FROM ACROSS EUROPE, CREATING THE PERFECT ENVIRONMENT TO APPLY HER MULTILINGUAL SKILLS IN REAL INTERNATIONAL SETTINGS.\n\nHER JOURNEY REFLECTS THE ESSENCE OF ATELIER SPOTLIGHTS: CURIOUS, GLOBALLY MINDED WOMEN WHO USE LANGUAGE TO EXPLORE THE WORLD, CONNECT CULTURES, AND PREPARE FOR INTERNATIONAL CAREERS.",
    imagePath: "pages/sefika buse.webp"
  },
  {
    name: "Iris",
    slug: "iris",
    heading: "CORPORATE STRATEGY & ESG PROFESSIONAL",
    body: "IRIS IS A CORPORATE PROFESSIONAL WORKING AT KRAFT HEINZ MEXICO AND BUILDING HER PATH IN GOVERNANCE, POLICY DEVELOPMENT, AND SUSTAINABILITY STRATEGY. THROUGH HER WORK WITH THE ATELIER, IRIS HAS REFINED HER ABILITY TO DISCUSS COMPLEX TOPICS SUCH AS ESG FRAMEWORKS, CORPORATE POLICIES, AND ORGANIZATIONAL STRATEGY IN ENGLISH WITH CLARITY AND PRECISION.\n\nHER PROGRAM FOCUSES ON DEVELOPING EXECUTIVE COMMUNICATION SKILLS—LEARNING HOW TO STRUCTURE IDEAS, PRESENT STRATEGIC INITIATIVES, AND CONFIDENTLY PARTICIPATE IN INTERNATIONAL CORPORATE CONVERSATIONS.\n\nIRIS REPRESENTS THE TYPE OF GLOBALLY MINDED PROFESSIONAL THE ATELIER WORKS WITH: AMBITIOUS, ANALYTICAL, AND COMMITTED TO OPERATING AT AN INTERNATIONAL LEVEL.",
    imagePath: "pages/iris.webp"
  },
  {
    name: "Carolina",
    slug: "carolina",
    heading: "FOOD ENGINEER & INDUSTRIAL TECHNICAL SPECIALIST",
    body: "CAROLINA IS A FOOD ENGINEER SPECIALIZING IN BAKING SCIENCE AND FERMENTATION. SHE CURRENTLY WORKS AS AN INDUSTRIAL TECHNICAL SPECIALIST AT AN INTERNATIONAL LEADING BAKERY COMPANY, WHERE SHE COLLABORATES WITH BAKERIES TO OPTIMIZE FERMENTATION PROCESSES, IMPROVE PRODUCT QUALITY, AND IMPLEMENT TECHNICAL SOLUTIONS IN INDUSTRIAL BAKING.\n\nWHEN CAROLINA BEGAN WORKING WITH THE ATELIER, HER GOAL WAS CLEAR: TO FINALLY DEVELOP THE CONFIDENCE AND FLUENCY IN ENGLISH THAT HER PROFESSIONAL CAREER REQUIRED. ALTHOUGH SHE HAD STUDIED ENGLISH FOR MANY YEARS, SHE STRUGGLED WITH VOCABULARY, SENTENCE STRUCTURE, AND SPEAKING NATURALLY IN PROFESSIONAL CONTEXTS.\n\nTHROUGH PERSONALIZED LESSONS FOCUSED ON REAL-WORLD TECHNICAL COMMUNICATION, CAROLINA BEGAN PRACTICING ENGLISH THROUGH THE TOPICS SHE KNOWS BEST: FOOD ENGINEERING AND HER DAILY WORK IN THE INDUSTRY. INSTEAD OF TRADITIONAL LANGUAGE EXERCISES, SHE LEARNS HOW TO EXPLAIN COMPLEX PROCESSES, DESCRIBE TECHNICAL PROBLEMS, AND COMMUNICATE WITH CLARITY IN PROFESSIONAL SETTINGS.\n\nAS HER ENGLISH PROGRESSED, SO DID HER CONFIDENCE. TODAY, CAROLINA REGULARLY DISCUSSES SCIENTIFIC TOPICS IN ENGLISH, EXPLAINS FERMENTATION AND BAKING PROCESSES WITH PRECISION, AND CONTINUES EXPANDING HER PROFESSIONAL VOICE THROUGH HER PERSONAL PROJECT BY QUIET AMBITION, WHERE SHE SHARES INSIGHTS ABOUT FOOD ENGINEERING, PROFESSIONAL GROWTH, AND LANGUAGE LEARNING.\n\nHER JOURNEY REFLECTS THE CORE PHILOSOPHY OF THE ATELIER: LEARNING A LANGUAGE BECOMES TRULY EFFECTIVE WHEN IT IS CONNECTED TO WHO YOU ARE, WHAT YOU LOVE, AND THE CAREER YOU ARE BUILDING.",
    imagePath: "pages/carolina.webp"
  },
  {
    name: "Valeria",
    slug: "valeria",
    heading: "HER A2 TO B2 ENGLISH JOURNEY",
    body: "VALERIA JOINED THE ATELIER WITH A GENERAL ENGLISH FOUNDATION AND A CLEAR GOAL: TO STRENGTHEN HER ENGLISH AND GAIN THE CONFIDENCE NEEDED TO COMMUNICATE IN MORE COMPLEX AND PROFESSIONAL CONTEXTS.\n\nTHROUGHOUT HER PROGRAM, WE WORKED INTENSIVELY ON DEVELOPING THE KEY SKILLS REQUIRED FOR UPPER-INTERMEDIATE ENGLISH. OUR SESSIONS FOCUSED ON ACADEMIC READING AND LISTENING, STRUCTURED WRITING, AND DISCUSSION-BASED SPEAKING INSPIRED BY INTERNATIONAL EXAMS SUCH AS IELTS, TOEFL IBT, CELEX, AND THE DUOLINGO ENGLISH TEST. TOGETHER, WE STRENGTHENED HER GRAMMAR FOUNDATION WHILE INTRODUCING MORE ADVANCED STRUCTURES SUCH AS RELATIVE CLAUSES, CONDITIONAL FORMS, AND ARGUMENTATIVE WRITING.\n\nBEYOND GRAMMAR AND VOCABULARY, VALERIA'S PROGRAM EMPHASIZED CRITICAL THINKING, IDEA DEVELOPMENT, AND THE ABILITY TO EXPRESS NUANCED OPINIONS IN ENGLISH — ESSENTIAL ABILITIES FOR REACHING THE B2 LEVEL.\n\nHER DEDICATION AND WILLINGNESS TO CHALLENGE HERSELF MADE EVERY SESSION DYNAMIC AND ENGAGING. OVER TIME, VALERIA DEVELOPED STRONGER FLUENCY, GREATER CONFIDENCE WHEN DISCUSSING COMPLEX TOPICS, AND A MUCH MORE STRUCTURED WAY OF EXPRESSING HER IDEAS IN ENGLISH.\n\nHER JOURNEY REFLECTS EXACTLY WHAT THE ATELIER AIMS TO BUILD: STUDENTS WHO DON'T JUST LEARN ENGLISH, BUT LEARN HOW TO THINK, COMMUNICATE, AND GROW THROUGH THE LANGUAGE.",
    imagePath: "pages/valeria.webp"
  },
  {
    name: "María Fernanda",
    slug: "maria",
    heading: "HISTORIAN - GOVERNMENT RESEARCHER",
    body: "MARÍA FERNANDA IS A HISTORIAN CURRENTLY STRENGTHENING HER ACADEMIC ENGLISH TO ENGAGE MORE CONFIDENTLY WITH INTERNATIONAL RESEARCH TO PURSUE A DOCTORAL DEGREE, FOCUSING ON CONFERENCES AND SCHOLARLY DISCUSSIONS. THROUGH THE ATELIER'S PERSONALIZED PROGRAM, SHE HAS FOCUSED ON DEVELOPING THE LANGUAGE TOOLS NEEDED TO ANALYZE HISTORICAL PROCESSES, EXPLAIN COMPLEX IDEAS, AND EXPRESS ACADEMIC ARGUMENTS CLEARLY IN ENGLISH.\n\nHER LESSONS COMBINE HISTORICAL ANALYSIS WITH STRUCTURED LANGUAGE PRACTICE, ALLOWING HER TO WORK ON TOPICS SUCH AS NATIONALISM, IDENTITY, AND HISTORICAL NARRATIVE WHILE REFINING THE GRAMMAR, VOCABULARY, AND LOGICAL CONNECTORS REQUIRED IN ACADEMIC CONTEXTS. AS PART OF HER PROGRESS, MARÍA FERNANDA NOW PRACTICES PRESENTING HISTORICAL ARGUMENTS, DISCUSSING RESEARCH QUESTIONS, AND WRITING SHORT ANALYTICAL TEXTS IN ENGLISH.\n\nHER JOURNEY REFLECTS THE ATELIER'S PHILOSOPHY: LANGUAGE LEARNING IS MOST POWERFUL WHEN IT SUPPORTS A STUDENT'S INTELLECTUAL IDENTITY AND PROFESSIONAL GOALS.",
    imagePath: "pages/maria fernanda.webp"
  },
  {
    name: "Arletthe",
    slug: "arletthe",
    heading: "FOOD ENGINEER & SALES PROFESSIONAL",
    body: "ARLETTHE JOINED THE PROGRAM TO STRENGTHEN HER ENGLISH AND EXPAND HER PROFESSIONAL OPPORTUNITIES. THROUGHOUT OUR WORK TOGETHER, OUR SESSIONS FOCUSED NOT ONLY ON LANGUAGE DEVELOPMENT BUT ALSO ON PRACTICAL COMMUNICATION, CAREER GROWTH, AND PERSONAL CLARITY. EACH CLASS WAS TAILORED TO HER GOALS, COMBINING ENGLISH PRACTICE WITH REAL-LIFE PROFESSIONAL AND PERSONAL TOPICS.\n\nAS ARLETTHE SHARES:\n\"EVERYTHING WENT REALLY WELL. THE CLASSES WERE NOT ONLY ABOUT LEARNING A LANGUAGE, BUT ABOUT LEARNING THAT, AND SO MANY OTHER THINGS. WORK-RELATED TOPICS, EMOTIONAL INTELLIGENCE, HABITS, MEDITATION — EVEN THE CLASSES AND ASSIGNMENTS HELPED ME A LOT DURING A MOMENT IN MY LIFE WHEN I WAS STRUGGLING WITH MANY THINGS.\n\nI REALLY LIKE THAT YOU FOCUS ON WHO THE PERSON IS, WHAT IS HAPPENING IN THEIR LIFE, AND HOW LEARNING A LANGUAGE CAN ALSO HELP THEM IMPROVE OTHER AREAS OF THEIR LIFE.\n\nI TRULY LIKE THE WAY YOU WORK.\"\n\nHER EXPERIENCE REFLECTS THE CORE PHILOSOPHY OF THE PROGRAM: LEARNING A LANGUAGE BECOMES FAR MORE MEANINGFUL WHEN IT CONNECTS TO A PERSON'S PROFESSIONAL AMBITIONS AND PERSONAL JOURNEY.",
    imagePath: "pages/arletthe.webp"
  }
];

export async function GET() {
  try {
    for (const s of spotlights) {
      await writeClient.createOrReplace({
        _type: 'spotlight',
        _id: `seed-${s.slug}`,
        name: s.name,
        slug: { _type: 'slug', current: s.slug },
        heading: s.heading,
        category: s.category || "ATELIER SPOTLIGHTS",
        body: s.body,
        // For images, we would normally upload asset, but for seeding we can just leave it to be manually linked or use a placeholder if needed.
        // Actually, I'll just skip the image field so the user can link it in Studio if they want, 
        // OR better yet, I'll just use the hardcoded paths in the frontend if image is missing.
      });
    }
    return NextResponse.json({ message: "Seeding successful" });
  } catch (err: any) {
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}
